# Generated by Django 5.0.3 on 2024-03-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_news_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='desc',
            field=models.CharField(max_length=120),
        ),
    ]
