# Generated by Django 5.0 on 2024-03-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="img_name",
        ),
        migrations.AddField(
            model_name="news",
            name="img",
            field=models.ImageField(blank=True, upload_to="news"),
        ),
        migrations.AddField(
            model_name="project",
            name="img",
            field=models.ImageField(blank=True, upload_to="projects"),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, default="", unique=True),
        ),
    ]
