# Generated by Django 5.0 on 2024-03-15 08:23

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_remove_news_img_name_news_img_project_img_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="content",
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=models.SlugField(blank=True, default="", unique=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="content",
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="desc",
            field=markdownx.models.MarkdownxField(),
        ),
    ]
